import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/auth-context";

export const metadata: Metadata = {
    title: "Eventorize",
    description: "Generated by DevForce"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>{children}</AuthProvider>
                <ToastContainer />
            </body>
        </html>
    );
}
